- name: "setup development environment"
  hosts: "*"
  gather_facts: true
  vars_files:
    - ../variables/variables.yml
  tasks:
    - name: install apt deps
      become: true
      apt:
        name:
          - ninja-build
          - gettext
          - cmake
          - unzip
          - curl
          - git
          - make
          - python3
          - python3-full
          - vim
          - ripgrep
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: install brew
      script: ../scripts/install-brew.sh
      args:
        creates: "{{ homebrew_dir }}/bin/brew"

    - name: check PATH
      shell:
        cmd: echo $PATH
      register: check_path

    - name: add homebrew to PATH
      shell:
        cmd: "PATH={{ homebrew_dir }}/bin:$PATH"
      when: check_path.stdout.find('brew') == -1

    - name: install deps (macos)
      shell:
        cmd: "{{ homebrew_dir }}/brew install ripgrep gettext cmake unzip curl git make python3 vim"
      when: ansible_facts['distribution'] == "MacOSX"

    - name: install build-essential deps for homebrew
      become: true
      apt:
        name:
          - build-essential
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: install pip
      script: ../scripts/install-pip.sh
      args:
        creates: /usr/local/bin/pip

    - name: install homebrew packages
      community.general.homebrew:
        name: fish,neovim,jesseduffield/lazygit/lazygit,zoxide,fzf

    - name: check ~/.bashrc file
      shell:
        cmd: cat {{ home_dir }}/.bashrc
      register: check_bash_rc

    - name: install rust
      script: ../scripts/install-rust.sh
      when: check_bash_rc.stdout.find('cargo') == -1

    - name: check /etc/shells for fish
      shell:
        cmd: cat /etc/shells
      register: get_shells

    - name: add fish to /etc/shells
      become: true
      shell:
        cmd: |
          echo "{{ homebrew_dir }}/bin/fish" | sudo tee -a /etc/shells
      when: get_shells.stdout.find('fish') == -1

    - name: set default shell to fish
      become: true
      user:
        name: "{{ user }}"
        shell: "{{ homebrew_dir }}/bin/fish"

    - name: check if fisher is installed
      stat:
        path: "{{ home_dir }}/.config/fish/fish_plugins"
      register: fisher_plugins

    - name: install fisher
      script: ../scripts/install-fisher.fish
      when: not fisher_plugins.stat.exists

    - name: install fisher plugins
      script: ../scripts/install-fish-plugins.fish

    - name: install node
      script: ../scripts/install-node.sh

    - name: install dotfiles
      script: ../scripts/install-dot-files.sh

    - name: configure tide prompt
      script: ../scripts/configure-tide-prompt.fish

    - name: check if docker is installed
      stat:
        path: /usr/bin/docker
      register: docker_ubuntu
      when:
        - ansible_facts['distribution'] == "Ubuntu"

    - name: check if docker is installed (macos)
      stat:
        path: /usr/local/bin/docker
      register: docker_macos
      when:
        - ansible_facts['distribution'] == "MacOSX"

    - name: install docker
      shell: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh
      when:
        - ansible_facts['distribution'] == "Ubuntu"
        - not docker_ubuntu.stat.exists

    - name: install docker (macos)
      community.general.homebrew:
        name: homebrew/cask/docker
        state: present
      when:
        - ansible_facts['distribution'] == "MacOSX"
        - not docker_macos.stat.exists
