- name: "setup development environment"
  hosts: "*"
  vars_files:
    - ../variables/variables.yml
  tasks:
    - name: install apt deps
      become: true
      apt:
        name:
          - ninja-build
          - gettext
          - cmake
          - unzip
          - curl
          - git
          - make
          - python3
          - python3-full
          - vim
        state: present

    - name: install brew
      script: ../scripts/install-brew.sh
      args:
        creates: /home/linuxbrew/.linuxbrew/bin/brew

    - name: install build-essential deps for homebrew
      become: true
      apt:
        name:
          - build-essential

    - name: install pip
      script: ../scripts/install-pip.sh
      args:
        creates: /usr/local/bin/pip

    - name: install fish
      shell:
        cmd: /home/linuxbrew/.linuxbrew/bin/brew install fish
      args:
        creates: /home/linuxbrew/.linuxbrew/bin/fish

    - name: check if neovim repo exists
      stat:
        path: "$HOME/neovim"
      register: neovim_repo

    - name: clone neovim repo
      shell:
        cmd: cd $HOME && git clone https://github.com/neovim/neovim
      when: neovim_repo.stat.isdir is not defined

    - name: cmake build neovim
      shell:
        cmd: cd $HOME/neovim && git checkout stable && make CMAKE_BUILD_TYPE=RelWithDebInfo
      args:
        creates: /usr/local/bin/nvim

    - name: install neovim
      become: true
      shell:
        cmd: cd {{ home_dir }}/neovim && sudo make install
      args:
        creates: /usr/local/bin/nvim

    - name: check ~/.bashrc file
      shell:
        cmd: cat $HOME/.bashrc
      register: check_bash_rc

    - name: install nvm & node
      script: ../scripts/install-nvm-and-node.sh
      when: check_bash_rc.stdout.find('nvm') == -1

    - name: install lazygit
      shell:
        cmd: /home/linuxbrew/.linuxbrew/bin/brew install jesseduffield/lazygit/lazygit
      args:
        creates: /home/linuxbrew/.linuxbrew/bin/lazygit

    - name: install rust
      script: ../scripts/install-rust.sh
      when: check_bash_rc.stdout.find('cargo') == -1

    - name: install lunarvim
      script: ../scripts/install-lunarvim.sh
      args:
        creates: "{{ home_dir }}/.local/bin/lvim"

    - name: get list of groups
      shell:
        cmd: compgen -g
      args:
        executable: /bin/bash
      register: get_groups

    - name: create chsh group
      become: true
      shell:
        cmd: |
          groupadd chsh
          usermod -a -G chsh {{ user }}
      when: get_groups.stdout.find('chsh') == -1

    - name: get chsh pam.d
      shell:
        cmd: cat /etc/pam.d/chsh
      register: get_pamd

    - name: add chsh group permissions to change shell
      become: true
      shell:
        cmd: |
          echo "auth       sufficient   pam_wheel.so trust group=chsh" | cat - /etc/pam.d/chsh > /tmp/out && sudo mv /tmp/out /etc/pam.d/chsh -f
      when: get_pamd.stdout.find('group=chsh') == -1

    - name: check /etc/shells for fish
      shell:
        cmd: cat /etc/shells
      register: get_shells

    - name: set fish as the default shell
      shell:
        cmd: |
          echo "/home/linuxbrew/.linuxbrew/bin/fish" | sudo tee -a /etc/shells
          chsh -s /home/linuxbrew/.linuxbrew/bin/fish {{ user }}
      when: get_shells.stdout.find('fish') == -1

    - name: add lunarvim and brew to PATH
      script: ../scripts/add-lunarvim-brew-to-path.fish

    - name: check if fisher is installed
      stat:
        path: $HOME/.config/fish/fish_plugins
      register: fisher_plugins

    - name: install fisher
      script: ../scripts/install-fisher.fish
      when: not fisher_plugins.stat.exists

    - name: install fisher plugins
      script: ../scripts/install-fish-plugins.fish

    - name: install dotfiles
      script: ../scripts/install-dot-files.sh

    - name: configure tide prompt
      script: ../scripts/configure-tide-prompt.fish

    - name: check if docker is installed
      stat:
        path: /usr/bin/docker
      register: docker

    - name: install docker
      shell: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh
      when: not docker.stat.exists
