- name: "update remote dependencies"
  hosts: "*"
  gather_facts: true
  vars_files:
    - ../variables/variables.yml
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
    - name: update dotfiles
      shell:
        cmd: "cd {{ dotfiles_dir }} && git pull && ./setup.sh"
      args:
        executable: "{{ homebrew_dir }}/bin/fish"
    - name: update brew and brew packages
      homebrew:
        update_homebrew: true
        upgrade_all: true
    - name: update node
      script: ../scripts/install-node.sh
    - name: update fisher plugins
      shell:
        cmd: "fisher update"
      args:
        executable: "{{ homebrew_dir }}/bin/fish"
